# Generated by Django 5.1 on 2024-09-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_task_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(),
        ),
    ]
